version: '3.7'

#  Define Services
services:
  # spring-boot service
  application:
    build:
      context: . # Configuration requires the path of the Dockerfile to be built relative to docker-compose.yml
      dockerfile: Dockerfile
    hostname:
      localhost
    ports:
      - "8080:8080" # Map native 8080 port to container 8080 port
    restart: always
    environment: # Setting environment variables
      spring.redis.host: 172.18.0.1